language: ruby
rvm:
  - 1.9.3
# - jruby-18mode # JRuby in 1.8 mode
# - jruby-19mode # JRuby in 1.9 mode
# - rbx-18mode
# - rbx-19mode
env:
# - DB=sqlite
# - DB=mysql
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
# - mysql -e 'create database name_app_test'
  - psql -c 'create database sample_app_test' -U postgres
